# Generated by Django 5.2 on 2025-04-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_page',
            new_name='Cover_Page',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='Price',
        ),
    ]
