# Generated by Django 5.2 on 2025-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_cover_page_book_cover_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
