# Generated by Django 5.2 on 2025-04-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_user_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='user',
            new_name='username',
        ),
    ]
