# Generated by Django 5.2 on 2025-04-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_user_user_registration_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='Book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cart_item',
        ),
    ]
