# Generated by Django 5.2 on 2025-04-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_username_user_registration_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
