# Generated by Django 5.2 on 2025-04-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
