# Generated by Django 5.2 on 2025-05-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_order_book_order_payment_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
